// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: crude/crude/query.proto

package crude

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName        = "/crude.crude.Query/Params"
	Query_SpecificUser_FullMethodName  = "/crude.crude.Query/specificUser"
	Query_AllUsers_FullMethodName      = "/crude.crude.Query/AllUsers"
	Query_UsersByAge_FullMethodName    = "/crude.crude.Query/UsersByAge"
	Query_UsersByGender_FullMethodName = "/crude.crude.Query/UsersByGender"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of SpecificUser items.
	SpecificUser(ctx context.Context, in *QuerySpecificUserRequest, opts ...grpc.CallOption) (*QuerySpecificUserResponse, error)
	// Queries a list of AllUsers items.
	AllUsers(ctx context.Context, in *QueryAllUsersRequest, opts ...grpc.CallOption) (*QueryAllUsersResponse, error)
	// Queries a list of UsersByAge items.
	UsersByAge(ctx context.Context, in *QueryUsersByAgeRequest, opts ...grpc.CallOption) (*QueryUsersByAgeResponse, error)
	// Queries a list of UsersByGender items.
	UsersByGender(ctx context.Context, in *QueryUsersByGenderRequest, opts ...grpc.CallOption) (*QueryUsersByGenderResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpecificUser(ctx context.Context, in *QuerySpecificUserRequest, opts ...grpc.CallOption) (*QuerySpecificUserResponse, error) {
	out := new(QuerySpecificUserResponse)
	err := c.cc.Invoke(ctx, Query_SpecificUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllUsers(ctx context.Context, in *QueryAllUsersRequest, opts ...grpc.CallOption) (*QueryAllUsersResponse, error) {
	out := new(QueryAllUsersResponse)
	err := c.cc.Invoke(ctx, Query_AllUsers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UsersByAge(ctx context.Context, in *QueryUsersByAgeRequest, opts ...grpc.CallOption) (*QueryUsersByAgeResponse, error) {
	out := new(QueryUsersByAgeResponse)
	err := c.cc.Invoke(ctx, Query_UsersByAge_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UsersByGender(ctx context.Context, in *QueryUsersByGenderRequest, opts ...grpc.CallOption) (*QueryUsersByGenderResponse, error) {
	out := new(QueryUsersByGenderResponse)
	err := c.cc.Invoke(ctx, Query_UsersByGender_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of SpecificUser items.
	SpecificUser(context.Context, *QuerySpecificUserRequest) (*QuerySpecificUserResponse, error)
	// Queries a list of AllUsers items.
	AllUsers(context.Context, *QueryAllUsersRequest) (*QueryAllUsersResponse, error)
	// Queries a list of UsersByAge items.
	UsersByAge(context.Context, *QueryUsersByAgeRequest) (*QueryUsersByAgeResponse, error)
	// Queries a list of UsersByGender items.
	UsersByGender(context.Context, *QueryUsersByGenderRequest) (*QueryUsersByGenderResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) SpecificUser(context.Context, *QuerySpecificUserRequest) (*QuerySpecificUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpecificUser not implemented")
}
func (UnimplementedQueryServer) AllUsers(context.Context, *QueryAllUsersRequest) (*QueryAllUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllUsers not implemented")
}
func (UnimplementedQueryServer) UsersByAge(context.Context, *QueryUsersByAgeRequest) (*QueryUsersByAgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersByAge not implemented")
}
func (UnimplementedQueryServer) UsersByGender(context.Context, *QueryUsersByGenderRequest) (*QueryUsersByGenderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsersByGender not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpecificUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpecificUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpecificUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpecificUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpecificUser(ctx, req.(*QuerySpecificUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_AllUsers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllUsers(ctx, req.(*QueryAllUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UsersByAge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsersByAgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UsersByAge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UsersByAge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UsersByAge(ctx, req.(*QueryUsersByAgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UsersByGender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsersByGenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UsersByGender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_UsersByGender_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UsersByGender(ctx, req.(*QueryUsersByGenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crude.crude.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "specificUser",
			Handler:    _Query_SpecificUser_Handler,
		},
		{
			MethodName: "AllUsers",
			Handler:    _Query_AllUsers_Handler,
		},
		{
			MethodName: "UsersByAge",
			Handler:    _Query_UsersByAge_Handler,
		},
		{
			MethodName: "UsersByGender",
			Handler:    _Query_UsersByGender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crude/crude/query.proto",
}
